version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    ports:
      - "4000:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: feeds
    volumes:
      - pgdata:/var/lib/postgresql/data

  embedding:
    build:
      context: ./embedding
    ports:
      - "8000:8000"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rss-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - embedding
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "chmod +x ./scripts/wait-for-it.sh &&
             ./scripts/wait-for-it.sh postgres:5432 -- npm run start:dev"

volumes:
  pgdata:
  redisdata: