version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: katchup
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api-server:
    build: ./api-server
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

  batch-server:
    build: ./batch-server
    depends_on:
      - db
      - embedding
    environment:
      SPRING_PROFILES_ACTIVE: prod

  embedding:
    build: ./embedding
    ports:
      - "8000:8000"

volumes:
  db_data: 