version: '3.8'
services:
  db:
    image: postgres:15.13
    environment:
      POSTGRES_DB: katchup
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api-server:
    build: ./api-server
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8080:8080"

  scheduler-server:
    build: ./scheduler-server
    depends_on:
      - db
      - embedding
    environment:
      SPRING_PROFILES_ACTIVE: prod

  embedding:
    build: ./embedding
    ports:
      - "8000:8000"

volumes:
  db_data: 