version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: feeds
    ports:
      - "4000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rss-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  pgdata:
  redisdata: